using System.ComponentModel.DataAnnotations;
// [Column] (rename the database column) lives in the .Schema namespace.
using System.ComponentModel.DataAnnotations.Schema;
// [JsonIgnore] controls System.Text.Json serialization for the Web API responses.
using System.Text.Json.Serialization;

namespace WEBTechnologies_Final.Models
{
    // A single bid placed by a user on a car. This is the "many" side of the
    // Car (one) -> Bids (many) relationship.
    public class Bid
    {
        // Primary key, auto-generated by the database.
        public int Id { get; set; }

        // Foreign key back to the Car this bid belongs to. EF Core links Bid.CarId to
        // Car.Id by convention, which is what makes Car.Bids and Bid.Car work.
        [Required]
        public int CarId { get; set; }

        // How much was bid. decimal is used for all money values (see Car.cs for why).
        [Required]
        public decimal Amount { get; set; }

        // Who placed the bid. [Column("BidderName")] tells EF to store this property in a
        // database column called "BidderName" even though the C# property is BidderUsername.
        // This is how you decouple a tidy C# name from a pre-existing/legacy column name.
        [Required]
        [Column("BidderName")]
        public string BidderUsername { get; set; } = string.Empty;

        // When the bid was made (UTC). Used to order the bid history.
        [Required]
        public DateTime CreatedUtc { get; set; } = DateTime.UtcNow;

        // Navigation property back to the parent car.
        // [JsonIgnore] stops the API from serializing it: without this, JSON serialization
        // would loop forever (Car -> Bids -> Car -> Bids ...). Note Program.cs ALSO sets
        // ReferenceHandler.IgnoreCycles as a global safety net for the same problem.
        [JsonIgnore]
        public Car? Car { get; set; }
    }
}
