namespace WEBTechnologies_Final.Models
{
    // A registered account, stored in the "Users" table.
    // The column is named PasswordHash because the INTENT is to store a hash, never the raw
    // password. STUDY CAVEAT: that intent is only honoured on the API path
    // (UsersApiController uses PasswordHasher). The MVC path (AccountController -> ApiClient)
    // currently stores and compares the password in PLAIN TEXT, so for web-registered users
    // this field actually holds the raw password. See ApiClient.RegisterAsync/ValidateAsync.
    public class User
    {
        // Primary key, auto-generated by the database.
        public int Id { get; set; }

        // Login name. Used as the user's identity throughout the app (bids, favourites and
        // the session all key off the username rather than the numeric Id).
        public string Username { get; set; } = string.Empty;

        public string Email { get; set; } = string.Empty;

        // Intended to hold the SHA-256 hash from Services/PasswordHasher.cs. As noted above,
        // only the API path actually hashes; the MVC register/login flow stores the raw
        // password here. (Making both paths hash consistently would be the correct fix.)
        public string PasswordHash { get; set; } = string.Empty;

        // When the account was created (UTC).
        public DateTime RegisteredUtc { get; set; } = DateTime.UtcNow;
    }
}
